DRIVE = (1,2,3,4)
FRONT_LEFT_MOTOR, REAR_LEFT_MOTOR, FRONT_RIGHT_MOTOR, REAR_RIGHT_MOTOR = DRIVE

JOYSTICK = 1

COMPRESSOR = (2,2)
COMPRESSOR_RELAY, COMPRESSOR_PRESSURE_SENSOR = COMPRESSOR

SHOOTER_SOLENOIDS = (1, 2, 3, 4)
RIGHT_SHOOTER_ON_SOLENOID, RIGHT_SHOOTER_OFF_SOLENOID, LEFT_SHOOTER_ON_SOLENOID, LEFT_SHOOTER_OFF_SOLENOID = SHOOTER_SOLENOIDS
RIGHT_SHOOTER_SOLENOIDS, LEFT_SHOOTER_SOLENOIDS = (RIGHT_SHOOTER_ON_SOLENOID, RIGHT_SHOOTER_OFF_SOLENOID), (LEFT_SHOOTER_ON_SOLENOID, LEFT_SHOOTER_OFF_SOLENOID)

HARVESTER_SOLENOIDS = (5,6,7,8)
RIGHT_HARVESTER_ON_SOLENOID, RIGHT_HARVESTER_OFF_SOLENOID, LEFT_HARVESTER_ON_SOLENOID, LEFT_HARVESTER_OFF_SOLENOID = HARVESTER_SOLENOIDS
RIGHT_HARVESTER_SOLENOIDS, LEFT_HARVESTER_SOLENOIDS = (RIGHT_HARVESTER_ON_SOLENOID, RIGHT_HARVESTER_OFF_SOLENOID), (LEFT_HARVESTER_ON_SOLENOID, LEFT_HARVESTER_OFF_SOLENOID)

HARVESTER_WHEELS = 5
